### ISSUE TITLE
line 23: printf: \033[1;32m: invalid number

### ISSUE THREAD

**Issue by Bugswriter** [Bugswriter/tuxi#30]
- `shell` zsh
- `Operating system/version`: Artix
- `Terminal name/version`: st
- `$TERM` st

## Steps to Reproduce the Problem
* tuxi how many people are in world

![image](https://user-images.githubusercontent.com/23283318/108263492-5c21a100-718c-11eb-874b-84dc5d77c5af.png)

## Expected Behavior
You know.

## Actual Behavior
You know

# PS
Now this happened because of some pull requests I merge I think it's one of the latest. I merged for POSIX compatibility.

**Comment by Bugswriter** [comment]
@officialcactar  bro I think You know why this is happened after https://github.com/Bugswriter/tuxi/pull/24 Can you take a look?

**Comment by colonvirus** [comment]
printf "%b---%b\n$*\n%b---%b\n" "$G" "$N" "$G" "$N"
to
printf "%b---%b\n%s\n%b---%b\n"  "$G" "$N" "$*" "$G" "$N"
fixes it

**Comment by Bugswriter** [comment]
Can you give me a pull request? Also are you sure. we will not get any shell code issue because .. It was very eventual I found this. There are high chances We will not know about bugs like this.

**Comment by colonvirus** [comment]
I'm cleaning up the code, and i'll pr later?

**Comment by colonvirus** [comment]
Same issue with         
```
msg() { printf "%b>%b $*\n" "$G" "$N"; } 
err() { printf "%b$*%b\n" "$R" "$N"; }
```

**Comment by Bugswriter** [comment]
yeah you take your time. But please do fix this.

**Comment by owl4ce** [comment]
Just matching a very little, does this only happen to me? `printf \t`
```cfg
Usage: tuxi <your question>
	tuxi <OPTIONS> <your question>
```

![image](https://user-images.githubusercontent.com/53987136/108265490-6d25de80-719b-11eb-873a-db4f63a37aa0.png)

**Comment by officialcactar** [comment]
My apologies for the late response. I was eating lunch.

**Comment by Bugswriter** [comment]
So are you guys sure now. .this issue is fixed? and I can close this?

**Comment by Genghius** [comment]
> So are you guys sure now. .this issue is fixed? and I can close this?

yes. Atleast in the non-rolled-back version it is.

**Comment by PoseidonCoder** [comment]
![image](https://user-images.githubusercontent.com/34260118/108305904-e1429100-715f-11eb-9cd6-e644199a2c47.png)
it's still not working for me

**Comment by owl4ce** [comment]
> ![image](https://user-images.githubusercontent.com/34260118/108305904-e1429100-715f-11eb-9cd6-e644199a2c47.png)
> it's still not working for me

Yes, you might want to try PR for the `develop` branch

**Top**: `main` branch

---

**Bottom (alias)**: https://github.com/Bugswriter/tuxi/pull/39#issuecomment-781038332

![image](https://user-images.githubusercontent.com/53987136/108307339-37efaf80-71e0-11eb-8024-ea269c3f3eb8.png)

**Comment by Bugswriter** [comment]
I think we already solved this issue. It's time to close this thread?

**Comment by Genghius** [comment]
yikes, can be closed already.
